
services:
  click_server:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
    volumes:
      - ./dbfiles:/var/lib/clickhouse
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./config.d:/etc/clickhouse-server/config.d/
      - ./users.d:/etc/clickhouse-server/users.d/
    networks:
      - jupynetwork  

networks:
  jupynetwork:
    external: true  
 