
FROM jupyter/all-spark-notebook:latest

USER root

RUN pip install pyspark
RUN pip install boto3
RUN pip install minio
RUN wget https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.2/hadoop-aws-3.3.2.jar -P /usr/local/spark/jars/
RUN wget https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.901/aws-java-sdk-bundle-1.11.901.jar -P /usr/local/spark/jars/

USER $NB_UID

EXPOSE 8888