services: 
  jupyter:
    image: jupyter/all-spark-notebook:latest
    ports:
      - '8888:8888'
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
    volumes:
      - ./notebooks:/home/jovyan/work  # Monte le répertoire local 'notebooks' dans le conteneur
     
      - ../spark/data:/home/jovyan/data  # Monte le répertoire local contenant les données dans le conteneur
    networks:
      - jupynetwork
    depends_on:
      - minio
      - spark-master
      - spark-worker-1
      - spark-worker-2
    command: start-notebook.sh --NotebookApp.token=''
    build:
      context: .
      dockerfile: Dockerfile
  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - jupynetwork
    volumes:
      - 'minio_data:/data'
    #  - './scripts:/scripts' 
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
      - MINIO_DEFAULT_BUCKETS=datalake
    
  #  entrypoint: /bin/bash -c "/scripts/create_buckets.sh && sleep 20 && /opt/bitnami/minio/bin/minio server /data"
  spark-master:
    image: bitnami/spark:3.5.0
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - '9090:8080'
      - '7077:7077'
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
    networks:
      - jupynetwork
    depends_on:
      - minio
  spark-worker-1:
    image: bitnami/spark:3.5.0
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
    
    networks:
      - jupynetwork

  spark-worker-2:
    image: bitnami/spark:3.5.0
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
     - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
    networks:
      - jupynetwork
  

networks:
  jupynetwork:
    driver: bridge

volumes:
  minio_data:
    driver: local
